# GET http://127.0.0.1:8000/todos/

# POST http://127.0.0.1:8000/todos
# Content-Type: application/json

# {
#     "head": "my fresh lst",
#     "description": "description for brief list",
#     "list": []
# }

# GET http://127.0.0.1:8000/todos/hCkbzbQD

# DELETE http://127.0.0.1:8000/todos/qd6naiSH

# PATCH http://127.0.0.1:8000/todos/lDHcFnwH
# Content-Type: application/json

# {
#     "head": "my new perfect header by ZEYNAL MARDANLI",
#     "description": "Zeynal made this description true"
# }

# GET http://127.0.0.1:8000/todos/KdCr5hAn



### USER

POST http://127.0.0.1:8000/users
Content-Type: application/json

{
    "username": "ZeynalMardanli",
    "mail": "zeynalmardanli4321@gmail.com",
    "password": "myspecialPassword@@1!!",
    "userID": "fsdfsdfsd3423"
}

